name: "Leonidas"
description: "Issue-to-PR automation powered by Claude Code"
author: "JeremyDev87"

branding:
  icon: "zap"
  color: "orange"

inputs:
  mode:
    description: "Operation mode: 'plan' or 'execute'"
    required: true
  anthropic_api_key:
    description: "Anthropic API key for Claude Code"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true
  model:
    description: "Claude model to use (overrides config)"
    required: false
  max_turns:
    description: "Maximum turns for Claude Code (overrides config)"
    required: false
  allowed_tools:
    description: "Comma-separated allowed tools (overrides config)"
    required: false
  branch_prefix:
    description: "Branch name prefix for PRs (overrides config)"
    required: false
  base_branch:
    description: "Base branch for PRs (overrides config)"
    required: false
  language:
    description: "Language for plan comments (overrides config)"
    required: false
  config_path:
    description: "Path to leonidas.config.yml"
    required: false
    default: "leonidas.config.yml"
  system_prompt_path:
    description: "Path to custom system prompt file"
    required: false
    default: ".github/leonidas.md"
  rules_path:
    description: "Path to rules directory containing .md files"
    required: false
    default: ".github/leonidas-rules"

outputs:
  conclusion:
    description: "Conclusion from Claude Code execution"
    value: ${{ steps.claude.outputs.conclusion }}
  execution_file:
    description: "Path to execution output file"
    value: ${{ steps.claude.outputs.execution_file }}
  branch_prefix:
    description: "Branch prefix used for this run"
    value: ${{ steps.prepare.outputs.branch_prefix }}
  base_branch:
    description: "Base branch used for this run"
    value: ${{ steps.prepare.outputs.base_branch }}
  language:
    description: "Language used for this run"
    value: ${{ steps.prepare.outputs.language }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install action dependencies
      shell: bash
      run: npm ci --prefix ${{ github.action_path }}

    - name: Build action
      shell: bash
      run: npm run build --prefix ${{ github.action_path }}

    - name: Prepare
      id: prepare
      shell: bash
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_MAX_TURNS: ${{ inputs.max_turns }}
        INPUT_ALLOWED_TOOLS: ${{ inputs.allowed_tools }}
        INPUT_BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        INPUT_LANGUAGE: ${{ inputs.language }}
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
        INPUT_SYSTEM_PROMPT_PATH: ${{ inputs.system_prompt_path }}
        INPUT_RULES_PATH: ${{ inputs.rules_path }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action/base-action@v1
      env:
        ANTHROPIC_MODEL: ${{ steps.prepare.outputs.model }}
        INPUT_MAX_TURNS: ${{ steps.prepare.outputs.max_turns }}
        INPUT_ALLOWED_TOOLS: ${{ steps.prepare.outputs.allowed_tools }}
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        prompt_file: ${{ steps.prepare.outputs.prompt_file }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        show_full_output: "true"
        use_node_cache: "false"

    - name: Cleanup prompt file
      if: always()
      shell: bash
      run: rm -f "${{ steps.prepare.outputs.prompt_file }}"

    - name: Link native sub-issues (if decomposed)
      if: inputs.mode == 'plan' && !failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: node dist/post_process/index.js link-subissues

    - name: Post completion comment
      if: inputs.mode == 'execute' && !failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        LANGUAGE: ${{ steps.prepare.outputs.language }}
        BRANCH_PREFIX: ${{ steps.prepare.outputs.branch_prefix }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: node dist/post_process/index.js post-completion

    - name: Rescue partial progress
      id: rescue
      if: failure() && inputs.mode == 'execute'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        BRANCH_PREFIX: ${{ steps.prepare.outputs.branch_prefix }}
        BASE_BRANCH: ${{ steps.prepare.outputs.base_branch }}
        LANGUAGE: ${{ steps.prepare.outputs.language }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        BRANCH_NAME="${BRANCH_PREFIX}${ISSUE_NUMBER}"

        # Set localized messages based on language
        case "$LANGUAGE" in
          ko)
            MSG_HEADER_PARTIAL="## ⚠️ 레오니다스 부분 진행"
            MSG_PR_EXISTS_BODY="구현이 중단되었습니다 (최대 턴 수에 도달했을 가능성이 있음). 하지만 PR이 존재합니다.\n\n**풀 리퀘스트:** #${EXISTING_PR}\n**상태:** 부분 구현 — 완료된 작업을 확인하려면 PR을 검토하세요.\n**워크플로 실행:** [로그 보기]($RUN_URL)\n\n**계속하려면:** 깨끗한 브랜치에서 다시 시도하려면 \`/approve\`를 다시 댓글로 달거나, PR을 수동으로 완료하세요."
            MSG_DRAFT_CREATED_BODY="구현이 중단되었지만, 진행 상황을 보존하기 위해 초안 PR이 생성되었습니다.\n\n**초안 PR:** ${PR_URL}\n**워크플로 실행:** [로그 보기]($RUN_URL)\n\n**계속하려면:** 다시 시도하려면 \`/approve\`를 댓글로 달거나, 초안 PR을 수동으로 완료하세요."
            MSG_PR_BODY_HEADER="## 부분 구현"
            MSG_PR_BODY_CONTENT="이 PR은 실행이 중단된 후 (최대 턴 수에 도달했을 가능성이 있음) 부분 진행 상황을 보존하기 위해 레오니다스에 의해 자동으로 생성되었습니다.\n\n**상태:** 불완전 — 수동으로 검토하고 계속하거나 다시 시도하세요.\n**워크플로 실행:** [로그 보기]($RUN_URL)\n\nCloses #${ISSUE_NUMBER}"
            ;;
          ja)
            MSG_HEADER_PARTIAL="## ⚠️ Leonidas 部分的な進行"
            MSG_PR_EXISTS_BODY="実装が中断されました（最大ターン数に達した可能性があります）が、PRが存在します。\n\n**プルリクエスト:** #${EXISTING_PR}\n**ステータス:** 部分的な実装 — 完了した作業を確認するにはPRをレビューしてください。\n**ワークフロー実行:** [ログを表示]($RUN_URL)\n\n**続行するには:** クリーンなブランチから再試行するには \`/approve\` を再度コメントするか、PRを手動で完了してください。"
            MSG_DRAFT_CREATED_BODY="実装が中断されましたが、進行状況を保存するためにドラフトPRが作成されました。\n\n**ドラフトPR:** ${PR_URL}\n**ワークフロー実行:** [ログを表示]($RUN_URL)\n\n**続行するには:** 再試行するには \`/approve\` をコメントするか、ドラフトPRを手動で完了してください。"
            MSG_PR_BODY_HEADER="## 部分的な実装"
            MSG_PR_BODY_CONTENT="このPRは、実行が中断された後（最大ターン数に達した可能性があります）、部分的な進行状況を保存するためにLeonidasによって自動作成されました。\n\n**ステータス:** 不完全 — 手動でレビューして続行するか、再試行してください。\n**ワークフロー実行:** [ログを表示]($RUN_URL)\n\nCloses #${ISSUE_NUMBER}"
            ;;
          zh)
            MSG_HEADER_PARTIAL="## ⚠️ Leonidas 部分进展"
            MSG_PR_EXISTS_BODY="实现已中断（可能达到最大轮数），但存在PR。\n\n**拉取请求:** #${EXISTING_PR}\n**状态:** 部分实现 — 查看PR以了解已完成的工作。\n**工作流运行:** [查看日志]($RUN_URL)\n\n**继续:** 再次评论 \`/approve\` 以从干净分支重试，或手动完成PR。"
            MSG_DRAFT_CREATED_BODY="实现已中断，但创建了草稿PR以保留进度。\n\n**草稿PR:** ${PR_URL}\n**工作流运行:** [查看日志]($RUN_URL)\n\n**继续:** 评论 \`/approve\` 重试，或手动完成草稿PR。"
            MSG_PR_BODY_HEADER="## 部分实现"
            MSG_PR_BODY_CONTENT="此PR由Leonidas自动创建，用于在执行中断后（可能达到最大轮数）保留部分进度。\n\n**状态:** 不完整 — 手动审查并继续或重试。\n**工作流运行:** [查看日志]($RUN_URL)\n\nCloses #${ISSUE_NUMBER}"
            ;;
          es)
            MSG_HEADER_PARTIAL="## ⚠️ Progreso Parcial de Leonidas"
            MSG_PR_EXISTS_BODY="La implementación se interrumpió (probablemente alcanzó el máximo de turnos), pero existe un PR.\n\n**Pull Request:** #${EXISTING_PR}\n**Estado:** Implementación parcial — revisa el PR para ver el trabajo completado.\n**Ejecución del workflow:** [Ver logs]($RUN_URL)\n\n**Para continuar:** Comenta \`/approve\` nuevamente para reintentar desde una rama limpia, o completa el PR manualmente."
            MSG_DRAFT_CREATED_BODY="La implementación se interrumpió, pero se creó un PR borrador para preservar el progreso.\n\n**PR Borrador:** ${PR_URL}\n**Ejecución del workflow:** [Ver logs]($RUN_URL)\n\n**Para continuar:** Comenta \`/approve\` para reintentar, o completa el PR borrador manualmente."
            MSG_PR_BODY_HEADER="## Implementación Parcial"
            MSG_PR_BODY_CONTENT="Este PR fue creado automáticamente por Leonidas para preservar el progreso parcial después de que la ejecución fue interrumpida (probablemente alcanzó el máximo de turnos).\n\n**Estado:** Incompleto — revisa y continúa manualmente o reintenta.\n**Ejecución del workflow:** [Ver logs]($RUN_URL)\n\nCloses #${ISSUE_NUMBER}"
            ;;
          *)
            MSG_HEADER_PARTIAL="## ⚠️ Leonidas Partial Progress"
            MSG_PR_EXISTS_BODY="Implementation was interrupted (likely hit max turns), but a PR exists.\n\n**Pull Request:** #${EXISTING_PR}\n**Status:** Partial implementation — review the PR for completed work.\n**Workflow run:** [View logs]($RUN_URL)\n\n**To continue:** Comment \`/approve\` again to retry from a clean branch, or manually complete the PR."
            MSG_DRAFT_CREATED_BODY="Implementation was interrupted, but a draft PR was created to preserve progress.\n\n**Draft PR:** ${PR_URL}\n**Workflow run:** [View logs]($RUN_URL)\n\n**To continue:** Comment \`/approve\` again to retry, or manually complete the draft PR."
            MSG_PR_BODY_HEADER="## Partial Implementation"
            MSG_PR_BODY_CONTENT="This PR was auto-created by Leonidas to preserve partial progress after the execution was interrupted (likely hit max turns).\n\n**Status:** Incomplete — review and continue manually or retry.\n**Workflow run:** [View logs]($RUN_URL)\n\nCloses #${ISSUE_NUMBER}"
            ;;
        esac

        # Check if the branch was pushed to remote
        if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
          echo "branch_exists=true" >> "$GITHUB_OUTPUT"

          # Check if a PR already exists for this branch
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

          if [ -n "$EXISTING_PR" ]; then
            echo "pr_exists=true" >> "$GITHUB_OUTPUT"
            echo "pr_number=$EXISTING_PR" >> "$GITHUB_OUTPUT"
            gh issue comment "$ISSUE_NUMBER" --body "${MSG_HEADER_PARTIAL}

        ${MSG_PR_EXISTS_BODY}"
          else
            # Build PR title with sub-issue metadata if available
            ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --json body --jq '.body' 2>/dev/null || echo "")
            PARENT_NUM=$(echo "$ISSUE_BODY" | grep -oP '<!--\s*leonidas-parent:\s*#\K\d+' || echo "")
            ISSUE_TITLE=$(gh issue view "$ISSUE_NUMBER" --json title --jq '.title')

            if [ -n "$PARENT_NUM" ]; then
              PR_TITLE="#${PARENT_NUM} ${ISSUE_TITLE} [partial]"
              PR_BODY="Part of #${PARENT_NUM}

        ${MSG_PR_BODY_HEADER}

        ${MSG_PR_BODY_CONTENT}"
            else
              PR_TITLE="#${ISSUE_NUMBER}: ${ISSUE_TITLE} [partial]"
              PR_BODY="${MSG_PR_BODY_HEADER}

        ${MSG_PR_BODY_CONTENT}"
            fi

            PR_URL=$(gh pr create \
              --draft \
              --head "$BRANCH_NAME" \
              --base "$BASE_BRANCH" \
              --title "$PR_TITLE" \
              --body "$PR_BODY" 2>&1 || echo "")

            if [ -n "$PR_URL" ]; then
              echo "pr_created=true" >> "$GITHUB_OUTPUT"
              gh issue comment "$ISSUE_NUMBER" --body "${MSG_HEADER_PARTIAL}

        ${MSG_DRAFT_CREATED_BODY}"
            fi
          fi
        else
          echo "branch_exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Post failure comment
      if: failure() && steps.rescue.outputs.branch_exists != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        LANGUAGE: ${{ steps.prepare.outputs.language }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        MODE: ${{ inputs.mode }}
      run: node dist/post_process/index.js post-failure

    - name: Post-process PR
      if: always() && inputs.mode == 'execute'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        BRANCH_PREFIX: ${{ steps.prepare.outputs.branch_prefix }}
      run: |
        BRANCH_NAME="${BRANCH_PREFIX}${ISSUE_NUMBER}"
        PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

        if [ -z "$PR_NUMBER" ]; then
          echo "No PR found for branch $BRANCH_NAME, skipping post-processing."
          exit 0
        fi

        echo "Post-processing PR #${PR_NUMBER}..."

        # Add labels from issue (excluding 'leonidas')
        LABELS=$(gh issue view "$ISSUE_NUMBER" --json labels --jq '[.labels[].name | select(. != "leonidas")] | join(",")' 2>/dev/null || echo "")
        if [ -n "$LABELS" ]; then
          echo "Adding labels: $LABELS"
          gh pr edit "$PR_NUMBER" --add-label "$LABELS" || echo "Warning: failed to add labels"
        fi

        # Add assignee from issue author
        AUTHOR=$(gh issue view "$ISSUE_NUMBER" --json author --jq '.author.login' 2>/dev/null || echo "")
        if [ -n "$AUTHOR" ]; then
          echo "Adding assignee: $AUTHOR"
          gh pr edit "$PR_NUMBER" --add-assignee "$AUTHOR" || echo "Warning: failed to add assignee"
        fi

    - name: Trigger CI on PR branch
      if: always() && inputs.mode == 'execute'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        BRANCH_PREFIX: ${{ steps.prepare.outputs.branch_prefix }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        BRANCH_NAME="${BRANCH_PREFIX}${ISSUE_NUMBER}"

        # Check if branch exists on remote
        if ! git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
          echo "Branch $BRANCH_NAME not found on remote, skipping CI trigger."
          exit 0
        fi

        echo "Triggering CI workflow on branch $BRANCH_NAME..."
        gh workflow run ci.yml --ref "$BRANCH_NAME" 2>&1 || echo "Note: Could not trigger CI via workflow_dispatch. CI may need to be triggered manually."
