name: "Leonidas"
description: "Issue-to-PR automation powered by Claude Code"
author: "JeremyDev87"

branding:
  icon: "zap"
  color: "orange"

inputs:
  mode:
    description: "Operation mode: 'plan' or 'execute'"
    required: true
  anthropic_api_key:
    description: "Anthropic API key for Claude Code"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true
  model:
    description: "Claude model to use (overrides config)"
    required: false
  max_turns:
    description: "Maximum turns for Claude Code (overrides config)"
    required: false
  allowed_tools:
    description: "Comma-separated allowed tools (overrides config)"
    required: false
  branch_prefix:
    description: "Branch name prefix for PRs (overrides config)"
    required: false
  base_branch:
    description: "Base branch for PRs (overrides config)"
    required: false
  language:
    description: "Language for plan comments (overrides config)"
    required: false
  config_path:
    description: "Path to leonidas.config.yml"
    required: false
    default: "leonidas.config.yml"
  system_prompt_path:
    description: "Path to custom system prompt file"
    required: false
    default: ".github/leonidas.md"

outputs:
  conclusion:
    description: "Conclusion from Claude Code execution"
    value: ${{ steps.claude.outputs.conclusion }}
  execution_file:
    description: "Path to execution output file"
    value: ${{ steps.claude.outputs.execution_file }}
  branch_prefix:
    description: "Branch prefix used for this run"
    value: ${{ steps.prepare.outputs.branch_prefix }}
  base_branch:
    description: "Base branch used for this run"
    value: ${{ steps.prepare.outputs.base_branch }}
  language:
    description: "Language used for this run"
    value: ${{ steps.prepare.outputs.language }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install action dependencies
      shell: bash
      run: npm ci --prefix ${{ github.action_path }}

    - name: Build action
      shell: bash
      run: npm run build --prefix ${{ github.action_path }}

    - name: Prepare
      id: prepare
      shell: bash
      env:
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_MAX_TURNS: ${{ inputs.max_turns }}
        INPUT_ALLOWED_TOOLS: ${{ inputs.allowed_tools }}
        INPUT_BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        INPUT_LANGUAGE: ${{ inputs.language }}
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
        INPUT_SYSTEM_PROMPT_PATH: ${{ inputs.system_prompt_path }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action/base-action@v1
      env:
        ANTHROPIC_MODEL: ${{ steps.prepare.outputs.model }}
        INPUT_MAX_TURNS: ${{ steps.prepare.outputs.max_turns }}
        INPUT_ALLOWED_TOOLS: ${{ steps.prepare.outputs.allowed_tools }}
        GH_TOKEN: ${{ inputs.github_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        prompt_file: ${{ steps.prepare.outputs.prompt_file }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        show_full_output: "true"
        use_node_cache: "false"

    - name: Link native sub-issues (if decomposed)
      if: inputs.mode == 'plan' && !failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.repository }}
      run: |
        # Find decomposed plan comment on this issue
        COMMENT_BODY=$(gh api "repos/$REPO/issues/$ISSUE_NUMBER/comments" \
          --paginate \
          --jq '[.[] | select(.body | contains("<!-- leonidas-decomposed -->"))] | last | .body // empty')

        if [ -z "$COMMENT_BODY" ]; then
          echo "No decomposed plan found, skipping sub-issue linking."
          exit 0
        fi

        echo "Decomposed plan found. Linking sub-issues to parent #$ISSUE_NUMBER..."

        # Extract sub-issue numbers from checklist (e.g., "- [ ] #36 — ...")
        SUB_ISSUES=$(echo "$COMMENT_BODY" | grep -oP '- \[[ x]\] #\K\d+' || true)

        if [ -z "$SUB_ISSUES" ]; then
          echo "No sub-issue numbers found in checklist."
          exit 0
        fi

        LINKED=0
        FAILED=0
        for SUB_NUM in $SUB_ISSUES; do
          # Get database ID (not node_id) of sub-issue
          DB_ID=$(gh api "repos/$REPO/issues/$SUB_NUM" --jq '.id' 2>/dev/null)

          if [ -z "$DB_ID" ]; then
            echo "Warning: Could not get DB ID for #$SUB_NUM"
            FAILED=$((FAILED + 1))
            continue
          fi

          echo "Linking #$SUB_NUM (DB ID: $DB_ID) as sub-issue of #$ISSUE_NUMBER"

          # Link as native sub-issue (idempotent — skip if already linked)
          if gh api "repos/$REPO/issues/$ISSUE_NUMBER/sub_issues" \
            -X POST -F "sub_issue_id=$DB_ID" 2>/dev/null; then
            LINKED=$((LINKED + 1))
          else
            echo "Warning: Failed to link #$SUB_NUM (may already be linked)"
            FAILED=$((FAILED + 1))
          fi
        done

        echo "Sub-issue linking complete: $LINKED linked, $FAILED skipped/failed."

    - name: Post completion comment
      if: inputs.mode == 'execute' && !failure()
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        LANGUAGE: ${{ steps.prepare.outputs.language }}
      run: |
        case "$LANGUAGE" in
          ko)
            MESSAGE="✅ **레오니다스**가 이슈 #${ISSUE_NUMBER}에 대한 구현을 완료했습니다. 자세한 내용은 풀 리퀘스트를 확인하세요."
            ;;
          ja)
            MESSAGE="✅ **Leonidas**がイシュー #${ISSUE_NUMBER} の実装を完了しました。詳細はプルリクエストをご確認ください。"
            ;;
          zh)
            MESSAGE="✅ **Leonidas** 已完成问题 #${ISSUE_NUMBER} 的实现。请查看拉取请求了解详情。"
            ;;
          es)
            MESSAGE="✅ **Leonidas** ha completado la implementación del issue #${ISSUE_NUMBER}. Consulta el pull request para más detalles."
            ;;
          *)
            MESSAGE="✅ **Leonidas** has completed the implementation for issue #${ISSUE_NUMBER}. Check the pull request for details."
            ;;
        esac
        gh issue comment "$ISSUE_NUMBER" --body "$MESSAGE"

    - name: Rescue partial progress
      id: rescue
      if: failure() && inputs.mode == 'execute'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        BRANCH_PREFIX: ${{ steps.prepare.outputs.branch_prefix }}
        BASE_BRANCH: ${{ steps.prepare.outputs.base_branch }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        BRANCH_NAME="${BRANCH_PREFIX}${ISSUE_NUMBER}"

        # Check if the branch was pushed to remote
        if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
          echo "branch_exists=true" >> "$GITHUB_OUTPUT"

          # Check if a PR already exists for this branch
          EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

          if [ -n "$EXISTING_PR" ]; then
            echo "pr_exists=true" >> "$GITHUB_OUTPUT"
            echo "pr_number=$EXISTING_PR" >> "$GITHUB_OUTPUT"
            gh issue comment "$ISSUE_NUMBER" --body "## ⚠️ Leonidas Partial Progress

        Implementation was interrupted (likely hit max turns), but a PR exists.

        **Pull Request:** #${EXISTING_PR}
        **Status:** Partial implementation — review the PR for completed work.
        **Workflow run:** [View logs]($RUN_URL)

        **To continue:** Comment \`/approve\` again to retry from a clean branch, or manually complete the PR."
          else
            # Create a draft PR to preserve the work
            PR_URL=$(gh pr create \
              --draft \
              --head "$BRANCH_NAME" \
              --base "$BASE_BRANCH" \
              --title "#${ISSUE_NUMBER}: $(gh issue view "$ISSUE_NUMBER" --json title --jq '.title') [partial]" \
              --body "## Partial Implementation

        This PR was auto-created by Leonidas to preserve partial progress after the execution was interrupted (likely hit max turns).

        **Status:** Incomplete — review and continue manually or retry.
        **Workflow run:** [View logs]($RUN_URL)

        Closes #${ISSUE_NUMBER}" 2>&1 || echo "")

            if [ -n "$PR_URL" ]; then
              echo "pr_created=true" >> "$GITHUB_OUTPUT"
              gh issue comment "$ISSUE_NUMBER" --body "## ⚠️ Leonidas Partial Progress

        Implementation was interrupted, but a draft PR was created to preserve progress.

        **Draft PR:** ${PR_URL}
        **Workflow run:** [View logs]($RUN_URL)

        **To continue:** Comment \`/approve\` again to retry, or manually complete the draft PR."
            fi
          fi
        else
          echo "branch_exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Post failure comment
      if: failure() && steps.rescue.outputs.branch_exists != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        gh issue comment "$ISSUE_NUMBER" --body "## ⚠️ Leonidas Failed

        The automated ${{ inputs.mode }} encountered an error.

        **Workflow run:** [View logs]($RUN_URL)

        **To retry:** $(if [ '${{ inputs.mode }}' = 'plan' ]; then echo 'Remove the \`leonidas\` label and re-add it.'; else echo 'Comment \`/approve\` again on this issue.'; fi)"
